### ISSUE TITLE
about funnels

### ISSUE THREAD

**Issue by zcswdt** [davidliyutong/canvas-cppgrader#1]
Hello, have you successfully trained? If so, I am willing to pay 1,000 yuan to get your guidance, thank you

**Comment by davidliyutong** [comment]
Hi, I'm sorry to inform you that we **didn't** managed to train cloth funnels, either. However, we did managed to set the PyFlex up. In case you need guidance about PyFlex, mail to equals_auction0v@icloud.com for details. I am closing this issue because it is irrelated to this project.
